/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Ryuism (https://sketchfab.com/Ryuism_)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/monster-boss-head-dragon-ec2e3d525dc24459a65d24b30da56e54
Title: Monster Boss Head Dragon
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Dragon(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../public/model/dragonB/scene.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log('B', actions);
    // console.log(materials);
    // console.log(animations);
    // if(previousAction){
    //   actions[previousAction].stop()
    // }
    actions.run.play();
    // useChangeColor(props.color);
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={12.762}>
          <group name="8031fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="8031">
                  <group name="GameObject" scale={1.25}>
                    <group name="F1_xueqilinzuoqi" rotation={[-Math.PI / 2, 0, 0]} scale={1.25} />
                    <group name="root">
                      <group name="Object_8">
                        <primitive object={nodes._rootJoint} />
                        <group name="Object_10" rotation={[-Math.PI / 2, 0, 0]} scale={[1.562, 1.563, 1.563]} />
                        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['8031_Material']} skeleton={nodes.Object_11.skeleton} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../public/model/dragonB/scene.gltf')
