/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: JesseDeGroot (https://sketchfab.com/JesseDeGroot)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/dae-villages-ulfs-viking-stylist-salon-28740d0a3481413b9457bbb21cdad877
Title: DAE Villages - Ulf's Viking Stylist Salon
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ShopHair(props) {
  const { nodes, materials } = useGLTF('../../public/model/hairShop/scene.gltf')
  useEffect(()=>{
    console.log("node", nodes);
    console.log("material", materials);
  },[])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Scene16_Building_0.geometry} material={materials.Building} />
      <mesh geometry={nodes.Scene16_Building_0_1.geometry} material={materials.Building} />
      <mesh geometry={nodes.Scene16_Environment_0.geometry} material={materials.Environment} />
    </group>
  )
}

useGLTF.preload('../../public/model/hairShop/scene.gltf')
